_target_: models.uncertainty.sota.hopcpt.HopCPTModel
# Context
ctx_mode: uni_past_multi_step_and_yhat
ctx_past_window: 1
#Context Encode
ctx_encode_hiddenL: 0
ctx_encode_dropout: null
ctx_encode_relu_before_hf: false
history_compress:
  mode: null
  window: null
pos_encode:
  mode: null
  dim: 5
# Memory
online_memory: true
online_mem_delay: null
keep_calib_eps: false
eps_mem_size: 8000
# Model
hopfield_beta: 1
head_per_alpha: False
eps_to_stored_pattern: False
score_transform: null # norm_by_ts_sd
# Train
batch_size: 4
batch_mode: one_ts
batch_mix_count: null
pub_training: False
use_memory_window: False
train_only_past: False
limit_train_seq_to_mem_size: False
limit_train_seq_stride: 10
predict_abs_eps: True
train_alphas: null
sample_alpha_train: null
# Inference Mix
mix_data_inference_mode: null
mix_data_inference_count: 3
mix_inference_draws: 1
mix_inference_sample_mem_size: null
pub_inference: False
# Inference Conformal
cached_inference: False
conf_selection: True
conf_eps_abs: False
conf_sel_beta: 0
mix_head_dist: True
sample_alpha_inference: False
conf_quantile_mode: sample
conf_quantile_topk: null
# Loss
loss_mode: mse
with_loss_weight: 0
coverage_loss_weight: 0
chung_loss_weight: 0
# Adaptive CI
use_adaptiveci: False
gamma: 0.005
