# @package _global_

#### Model params #############################################################
model:
  name: RExCP_sampling
  hparams: {}
  encoder:
    name: reservoir # rnn
    hparams:
      n_internal_units: 512 # reservoir_size
      leak: 0.75
      spectral_radius: 0.9
      input_scaling: 0.7
      noise_level: 0.0
      connectivity: 0.2
      circle: false
      dimred_method: null
  decoder:
    name: multiquantile
    hparams:
      hidden_size: ${model.encoder.hparams.n_internal_units}
