# @package _global_

#### Dataset params ###########################################################
dataset:
  name: exchange
  connectivity:
    method: identity
    layout: edge_index

#### Windowing params #########################################################
window: 30 # daily data
horizon: 1
stride: 1
delay: 0 # 11 -> start the prediction after delay steps (predict t + delay + 1)

scale_target: False
add_exogenous: True