# @package _global_

#### Dataset params ###########################################################
dataset:
  name: solar
  connectivity:
    method: identity
    layout: edge_index

#### Windowing params #########################################################
window: 24 # 12
horizon: 1 #12
stride: 1
delay: 0 # 11 -> start the prediction after delay steps (predict t + delay + 1)

scale_target: False
add_exogenous: False