### HYDRA START
hydra:
  run:
    dir: ./outputs/${hydra.job.name}
  sweep:
    dir: ./outputs/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    chdir: True # change working directory of run
    name: ${config.experiment_data.experiment_name}_${now:%d%m%y_%H%M%S}
#  launcher:
#    n_jobs: 6
#    prefer: processes
#    pre_dispatch: 1
### HYDRA END

### RUN CONFIG START
run_config:
  exec_type: parallel # sequential
  gpu_ids: [0]
  runs_per_gpu: 1    # Only relevant for parallel execution
  seeds:
    - 10
    - 20
    - 30
    - 40
#  skip_cfg: # fp_cfg / seed
#    - [0, 10]
#    - [2, 20]
  init_models: null

sweep:
  type: grid
  axes:
    - parameter: evaluation.pred_vega
      vals:
        - False
### RUN CONFIG END

###################################
defaults:
  - _self_
  - model_fc@config.model_fc: global_rnn
  - model_uc@config.model_uc: rccp
  - dataset@config.dataset: bejing_air_pm10
  - task@config.task: default_3year_gn
  - evaluation@config.evaluation: default


config:

  ### EXPERIMENT CONFIG
  experiment_data:
    base_proj_dir: null    # USE ABSOLUTE PATH!
    data_dir: ${config.experiment_data.base_proj_dir}data
    model_dir: ${config.experiment_data.base_proj_dir}models_save
    evaluate: true
    experiment_name: rccp_benchmark
    experiment_dir: null
    seed: 10
    gpu_id: 0

  trainer:
    _target_: trainer.internal_trainer.ModelInternalTrainer
    trainer_config:
      n_epochs: 3000
      val_every: 5
      save_every: 10000
      early_stopping_patience: 10
      optim:
        _target_: torch.optim.Adam
        _partial_: true
        lr: 0.003
        weight_decay: 0.0
      lr_scheduler: null
      grad_clip_param: null
      #  max_norm: 1
      model_selection: winkler
      init_model: null
  ###
